### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by dillythecoder** [Tindi12/Gary-AI#1]
When will this AI system be finished

**Comment by Tindi12** [comment]
after Im done my exams...which will prolly take one month (whole of october) and Im moving to another country on November so I plan on resuming all work on my projects around January.

**Comment by dillythecoder** [comment]
Well You shoudl be able to do like 30 min of it per day not that hard

**Comment by Tindi12** [comment]
Bruh...that 30 mins could have been spent studying or preparing for exams..they are in one week and will last 2-3 weeks then one more week of break and then another week of doing another round of exams..technically, i cant spend anytime

**Comment by dillythecoder** [comment]
But You can spend ur time on discord for multiple hours???? intresting

**Comment by Tindi12** [comment]
My acc is left on, i follow something called a pomodoro technique and we are in different time zones (15 hrs difference) 
pls stop diverting away from the topic thank you

**Comment by dillythecoder** [comment]
Still doesnt change the fact you talk on there for quite some times :)

**Comment by Tindi12** [comment]
so? Im pretty much ready dilly! all im saying is 'Im taking a break from code for some months bc of big interesting things going on in my life... and i use discord for sophisticated reasons unlike you who uses it to rasie useless arguments such as these on my github, and also attacking me on discord. pls stop

**Comment by dillythecoder** [comment]
Im sorry you were the one showing off and bragging ur a better coder to everyone and thought it was funny when it wasnt. Im simply asking you to provide some evidence in which obviuosly you cant. SO i recommend next time you talk to someone not to overtalk ur self

**Comment by Tindi12** [comment]
Aight, Im sick of this, Fuck off dilly, fine ur a better programmer, u dont understand I was joking around back then but it has been 2 fucking months and u cant seem to understand that it was a joke and get over it shows how immature and too much of a fuckwit to understand and act like you are mature but instead i wouldn't be surprised to find out that ur a fucking 9 year old. STOP it.

**Comment by Tindi12** [comment]
this is supposed to be regarding the project
not some argument from 2 months ago..

**Comment by dillythecoder** [comment]
its not joking its really messed up. And can you please not cuss its really innaprorpiate. And your the one acting immature saying ur the best. Please stop!!! Thanks

**Comment by Tindi12** [comment]
Fuck You dilly fuck you i only said im a better programmer bc i was joking around....and u call that messed up?
pretty much my definition of Immature

**Comment by dillythecoder** [comment]
WOW not approrpiate. And fix your grammar kid. Also as I said its not a joke and its not funny. Ur immature please be quiet

**Comment by Tindi12** [comment]
bruh stop this here..first on discord then here ur on my project raising an issue thats useless

**Comment by dillythecoder** [comment]
No one views it

**Comment by Tindi12** [comment]
really? now ur gonna get rude?

**Comment by dillythecoder** [comment]
Im sorry you just cussed at me and im stating facts

**Comment by Tindi12** [comment]
ok dilly:
-ur the better programmer       -u have better time management
-ur more efficient                      -ur better at comp scie theoretically and in action
-ur smarter
happy now? happy?

**Comment by dillythecoder** [comment]
Uhh yeah ig ty
